CREATE DATABASE LOGINFORM;

USE LOGINFORM;

CREATE TABLE LOGINS (
ID INT IDENTITY(1,1),
USUARIO VARCHAR(50) NOT NULL,
CLAVE VARCHAR(50) NOT NULL
CONSTRAINT PK_LOGINS PRIMARY KEY (ID)
);

INSERT INTO LOGINS (USUARIO,CLAVE) VALUES ('ADMIN','1234');
INSERT INTO LOGINS (USUARIO,CLAVE) VALUES ('VALENTINA','1234');
INSERT INTO LOGINS (USUARIO,CLAVE) VALUES ('RAIN','1234');
INSERT INTO LOGINS (USUARIO,CLAVE) VALUES ('AGUSTIN','1234');


CREATE PROCEDURE SP_LOGIN
@USUARIO_INGRESADO VARCHAR(50),
@CLAVE_INGRESADA VARCHAR(50)
AS
  BEGIN
  SELECT TOP 1 COUNT(*)
  FROM LOGINS 
  WHERE LOGINS.USUARIO = @USUARIO_INGRESADO
  AND LOGINS.CLAVE = @CLAVE_INGRESADA
  END;

  --PRUEBA USER & CLAVE BIEN
  EXECUTE SP_LOGIN 'VALENTINA','1234'
  -- PRUEBA USER & CLAVE MAL
  EXECUTE SP_LOGIN 'VALENTINA','3333'

 